site_name: AzCam

theme:
  name: material
  palette:
    primary: 'blue'
  logo:
    img/logo.png
  favicon:
    img/favicon.ico
  features:
    - navigation.sections
markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - attr_list

extra_css:
    - css/custom.css
    
